### ISSUE TITLE
symfony 2.7.3

### ISSUE THREAD

**Issue by elgui02** [TeckHouse/AnalyticsBundle#2]
Hi, i just wanna tray your bundle on symfony 2.7.3, when i register the bundle have this error on console " [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  Unable to replace alias "doctrine_mongodb" with "teckhouse_analytics.document_manager". " any ideas?

**Comment by mfoti** [comment]
uhm no, this project is not maintained if you want to PR will be appreciated :)

**Comment by ghost** [comment]
Hello skler, I got the same error as elgui02 commeted on 18 Aug 2015, I am willing to be a maintiner for AnalyticsBundle. Can you point to what to do to possibly resolve the error for our great open source community. we are of course very thankful to your great work.

**Comment by ghost** [comment]
Hello guys,

I have successfully resolve the error from a clean install (if you already ran into this error you will need to uninstall analyticsBundle completely before for these steps here is how:

1- Install DoctrineMongoDBBundle http://symfony.com/doc/master/bundles/DoctrineMongoDBBundle/index.html
2- Install MongoDB Server
https://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/
3- Install AnalyticsBundle
http://knpbundles.com/TeckHouse/AnalyticsBundle
4- this is OPTIONAL, it is an GUI for admin http://robomongo.org/
5- install StofDoctrineExtensionsBundle
https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html
6- this is OPTONAL, if you want to know how DoctrineMongoDBBundle works as an similar example of this analyticsBundle here is an official tutorial http://symfony.com/doc/master/bundles/DoctrineMongoDBBundle/index.html

Done.
